export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const GET_CART_NUMBERS = 'GET_CART_NUMBERS';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';